### ISSUE TITLE
Klax TTN V3

### ISSUE THREAD

**Issue by noll89** [dasdigidings/The_Things_Stack_v3-payload_functions#1]
Ist es möglich den Decoder direkt im ttn zu hinterlegen? 
In der Version ist nur noch ein Decoder mit max 4096 zeichen zugelassen

**Comment by Drasek** [comment]
Es ist möglich den Decoder direkt zu hinterlegen, das geschieht über das device-repo, welches hier auf github von TTI verwaltet wird. Dort haben Unternehmen die Möglichkeit Metadaten (welche LoRaWAN Version, etc. bis hin zum Payload Decoder) ihrer Produkte zu hinterlegen, so dass diese beim Anlegen eines Devices nur noch ausgewählt werden müssen und alle Einstellungen automatisch vorgenommen werden. Wir sehen das als Aufgabe der jeweiligen Unternehmen an, da diese auch das Geld damit verdienen diese Sensoren zu verkaufen und das zum normalen Support gehören sollte (ohne den Decoder ist das Gerät im TTN praktisch wertlos) und sehen nicht ein dafür unsere ehrenamtliche Arbeitszeit einzusetzen - da geh ich lieber ein Bier aufmachen und werfe den Grill an, oder halte einen Programmierkurs für Kinder & Jugendliche in der Zeit...

Kontakt zum Hersteller findest Du hier: [alpha-omega-technology.de/kontakt](https://alpha-omega-technology.de/kontakt)

**Comment by jensileinchen** [comment]
i will close that one as it seems to be solved !
