### ISSUE TITLE
Tabs decoder gives wrong "decoded_payload" when payload.bytes is empty [ ]

### ISSUE THREAD

**Issue by jensileinchen** [dasdigidings/The_Things_Stack_v3-payload_functions#2]
If "payload.uplink_message.decoded_payload.bytes" is [ ] the "payload.uplink_message.decoded_payload" gives out strange / wrong values .... we found this problem in the Grafana-Visualisation of our TABS TBDW100 (Door & Window) -- from time to time there are messages from the devices with empty bytes-array of the recieved payload. This causes 2.50 V, some temperature deep minus degrees (for indoor rooms).  I think the decoder should check the content of the payload array to avoid these values. Thanks for checking this !

![photo_2022-03-17_12-20-16](https://user-images.githubusercontent.com/43203851/158798432-89875f87-8ba1-4258-a145-831d821368ba.jpg)

**Comment by Drasek** [comment]
There is a new commit (https://github.com/dasdigidings/The_Things_Stack_v3-payload_functions/commit/a3f1aff6141b072e6f216ffe73a59e72b67d447a) with added error handling in case of a missing payload or the payload beeing the wrong length/size. Please test it and report back wether i nailed all the cases or not!

**Comment by jensileinchen** [comment]
Wow - this was quick-response - many thanks for that and your immediate help ! i will check the values in the next days and give feedback on this issue.

**Comment by jensileinchen** [comment]
tbdw100 decoder seems to be fine now -- all of my 12 devices are sending regular as before - but none of it sends -32°C or 2.5Volts (as done before with empty payload-array) --- i will close this issue here - thanks @Drasek for investigation !
